theme: jekyll-theme-slate
title: SOAP Message Viewer
description: A SOAP log message viewer utility for Windows.
show_downloads: true

github:
  zip_url: https://github.com/Sphinkie/SOAP-Message-Viewer/releases/latest/download/SOAP-MessageViewer.Portable.zip
  owner_name: David de Lorenzo
  owner_url: https://sphinkie.github.io/
